### ISSUE TITLE
Still works

### ISSUE THREAD

**Issue by bengalih** [danrahn/PlexSubtitleExtractor#1]
Found this GH as well as a post on /r from you.  Re-evaluating how subtitles are handled now that OpenSubstitles is basically locking everyone out.

Just wanted to say this worked well for me, but I had a few issues.  Only one that really you might be able to enhance.
Apparently my Plex install still had a default library in the default location, but due to a migration (I think) my Plex db was actually in another location.  Your script found the default library (not touched in years) and then gave out with errors because the appropriate DB fields were not there.

I figured this out by adding some debug print statements and then I just deleted my unused library files from the default location so the app prompted me for the right ones.

Unfortunately, I actually physically move my media into separate folders (still in libraries) after they are watched and it appears if you do this the metadata doesn't follow them.  So even though I have been downloading subtitles for years, I only had about 30 that exported.

The one enhancement I would make (in addition to better error control for issues like above), is to add the option to export the subtitles to the same folder that the media file is in.  I expect since you are able to extract the name of the file you can probably extract it's path fairly easily (though I haven't looked at the db myself).  This could be problematic in some scenarios depending on where the files are stored (local/network), but really if you have a large db of subtitles trying to pair them all back up with their media files would be pretty time intensive when you export them all to separate locations.

Also, a log file that gives just a straightforward listing of all subtitles exported and their locations would also be great (especially if adding the option to go to their folder location), just as a sanity check.

Not sure I will need this going forward, but its nice to know this option exists.
thanks!

**Comment by danrahn** [comment]
Thanks for the feedback! The original script was whipped up pretty quickly, so definitely has some rough edges that you've rightly pointed out. Saving subtitles alongside the media is something I've thought about before, but never really had a reason to implement yet. I'll push some changes soon that should address most of what you mentioned.
