### ISSUE TITLE
Error ! 

### ISSUE THREAD

**Issue by Aabayoumy** [danrahn/PlexSubtitleExtractor#2]
thank you for great tool :)

sudo python3 ./ExtractSubtitles.py --save-inline  -d /var/lib/plex/Plex\ Media\ Server/Plug-i
n\ Support/Databases/ -v
Traceback (most recent call last):
  File "/home/abayoumy/./ExtractSubtitles.py", line 265, in <module>
    process()
  File "/home/abayoumy/./ExtractSubtitles.py", line 92, in process
    if cmd_args.save_inline and cmd_args.output:
                                ^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'output'

**Comment by danrahn** [comment]
Thanks for the report! I renamed `output` to `output_dir`, but forgot to change it here. It should be fixed with 1b4bd434be9cf7e2ce5d8a5da34a09d83570aff8.
